// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXC65GfEc1wmExG1JS1XurMIjFP7sKo5g',
    appId: '1:408771882406:web:06d222ed2ae7a283ccb367',
    messagingSenderId: '408771882406',
    projectId: 'at-badminton',
    authDomain: 'at-badminton.firebaseapp.com',
    storageBucket: 'at-badminton.firebasestorage.app',
    measurementId: 'G-3CPJTR4521',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiymjLbz4omzhyWDmI7c4m_qpxlxU_lIA',
    appId: '1:408771882406:android:7f231697f2eb49dcccb367',
    messagingSenderId: '408771882406',
    projectId: 'at-badminton',
    storageBucket: 'at-badminton.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmwoBgSeXT5f2FLSkB1T1KFWpSKPkPiYs',
    appId: '1:408771882406:ios:e7ae552ddc2ddff8ccb367',
    messagingSenderId: '408771882406',
    projectId: 'at-badminton',
    storageBucket: 'at-badminton.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmwoBgSeXT5f2FLSkB1T1KFWpSKPkPiYs',
    appId: '1:408771882406:ios:e7ae552ddc2ddff8ccb367',
    messagingSenderId: '408771882406',
    projectId: 'at-badminton',
    storageBucket: 'at-badminton.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXC65GfEc1wmExG1JS1XurMIjFP7sKo5g',
    appId: '1:408771882406:web:96613bcdaa6d6f41ccb367',
    messagingSenderId: '408771882406',
    projectId: 'at-badminton',
    authDomain: 'at-badminton.firebaseapp.com',
    storageBucket: 'at-badminton.firebasestorage.app',
    measurementId: 'G-8KVVRK5M8K',
  );
}
